services:
  db:
    image: postgres:15.3-alpine3.18
    container_name: db
    env_file:
      - .env.prod
    volumes:
      - app_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.11-alpine3.18
    container_name: redis_app
    env_file:
      - .env.prod

  app:
    build:
      context: .
    env_file:
      - .env.prod
    container_name: trading_app
    command: sh -c "
        alembic upgrade head
        && gunicorn src.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
      "
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env.prod
    container_name: celery_app
    command: sh -c "celery --app=src.tasks.tasks:celery worker -l INFO"
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env.prod
    container_name: flower_app
    command: sh -c "celery --app=src.tasks.tasks:celery flower"
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555

volumes:
  app_db_data: