"""Initial

Revision ID: 1779a4b45d26
Revises: 1f1f25dfc1dc
Create Date: 2023-05-24 21:43:15.089106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1779a4b45d26'
down_revision = '1f1f25dfc1dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
